---
- name: Ensure required packages for NRPE server are present
  apt: "name={{ item }} state=present"
  with_items:
    - nagios-plugins
    - nagios-nrpe-server
    - python-dev

- name: Ensure required packages for the check_cpu plugins are present
  apt:
    name: bc
    state: present

- name: Ensure that the Nagios NRPE server port is allowed in the iptables
  iptables: chain=INPUT protocol=tcp destination_port="{{ nagios_nrpe_server_port }}" jump=ACCEPT

- name: Ensure that the NRPE server is running and will be started at boot time
  service: name=nagios-nrpe-server state=started enabled=yes
